paths:
  model_note: Berlin
perform_sweep: True
parameter_space:
  seed: !sweep
    default: 5
    range: [10]
  num_epochs: 20
  write_start: 1
  write_every: 10
  Covid_mob:
    Data:
      load_from_dir: data/Covid_mob/Berlin_data/data.csv
#      time_dependent_parameters:
      synthetic_data:
        dt: 0.1
      training_data_size: !slice [0, 200] #182]
    Data_weathermob:
      load_from_dir: data/Covid_mob/Berlin_data/weather_mobility.csv
      training_data_size: !slice [ 0, 200 ] #182]
    NeuralNet:
      num_layers: 3
      nodes_per_layer:
        default: 20
      activation_funcs:
        default: sigmoid
        layer_specific:
          -1: abs
      learning_rate: 0.002
      optimizer: Adam
    Training:
      batch_size: 200
      Berlin_data_loss: True
      loss_function:
        name: MSELoss
        kwargs:
          reduction: none # Do not sum over k
