Data:
  synthetic_data:

    # ODE model parameters
    k_E:  3.4
    k_R: 0.8
    k_D:  0.3

    # Number of steps to run
    num_steps: 200 #was 200 before

    # Discard an initialisation period
    burn_in: 10

    # Time differential to use for the solver
    dt: 0.1

NeuralNet:
  num_layers: !is-positive-int 2
  nodes_per_layer:
    default: !is-positive-int 20
  biases:
    default: ~
  activation_funcs:
    default: sigmoid
    layer_specific:
      -1: abs
  learning_rate: !is-positive 0.002

Training:
  batch_size: !is-positive-int 200 #was 200 before
  loss_function:
    name: MSELoss
    kwargs:
      reduction: sum
  to_learn: [k_E, k_R, k_D]
  device: cpu
  num_threads: ~
