paths:
  model_note: Berlin
perform_sweep: True
parameter_space:
  seed: !sweep
    default: 5
    range: [20]
  num_epochs: 2000
  write_start: 1
  write_every: 10
  Covid_lessdat:
    Data:
      load_from_dir: data/Covid_lessdat/Berlin_Brandenburg_data/data_2003_2009.csv
      time_dependent_parameters:
        k_E:
          - [ 0, 10 ] # Feb 16 to Mar 13 #[ 0, 10, 19, 64, 104, 182, 238 ]
          - [ 10, 19] # Mar 13 to Mar 22
          - [ 19, 64 ] # Mar 22 to May 6
          - [ 64, 104 ] # May 6 to June 15
          - [ 104, 184 ] # June 15 to Sep 3
          - [ 184, 202 ] # Sep 3 to Sep 21
          - [ 202, ~ ] # Sep 21 to Sep 30
#[0, 10, 19, 64, 104, 182, 242, 266, 286, 292, 302, 454] #[ 0, 26, 35, 80, 120, 200, 254 ]
#          labels: [ 'Mar 3', '', 'Mar 13–22', 'May 6', 'June 15', 'Sep 3', 'Nov 2', 'Nov 26', '', 'Dec 16-22', 'Jan 1', 'May 30' ]
      synthetic_data:
        dt: 0.1
      training_data_size: !slice [0, 211] # you had 200] #182]
    NeuralNet:
      num_layers: 3
      nodes_per_layer:
        default: 20
      activation_funcs:
        default: sigmoid
        layer_specific:
          -1: abs
      learning_rate: 0.002
      optimizer: Adam
    Training:
      batch_size: 211 # was 200 before
      Berlin_data_loss: True
      loss_function:
        name: MSELoss
        kwargs:
          reduction: none # Do not sum over k
